// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	FirstName string
	LastName  sql.NullString
	CreatedAt time.Time
}
