// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const getByID = `-- name: GetByID :one
SELECT id, first_name, last_name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}
