// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const getByTelegramID = `-- name: GetByTelegramID :one
SELECT id, telegram_id, first_name, last_name, username, created_at
FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
