name: Go Generate
env:
  GO_VERSION: '1.23'
on:
  push:

permissions:
  contents: write

jobs:
  sqlc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for changes in specific files
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

        if echo "$CHANGED_FILES" | grep -qE 'internal/db/query.sql|db/migrations/'; then
          echo "Changes detected in internal/db/query.sql or db/migrations/"
        else
          echo "No relevant changes detected, skipping remaining steps." >> $GITHUB_STEP_SUMMARY
          exit 0
        fi

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: Cache SQLC
      uses: actions/cache@v4
      with:
        path: ~/.cache/sqlc
        key: "${{ runner.os }}-sqlc-${{ hashFiles('**/go.sum') }}"
        restore-keys: |
          ${{ runner.os }}-sqlc-

    - name: Install SQLC
      run: |
        if [ ! -d ~/.cache/sqlc ]; then
          mkdir -p ~/.cache/sqlc
          GOBIN=~/.cache/sqlc go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
        fi
        echo "~/.cache/sqlc" >> $GITHUB_PATH

    - name: Generate SQLC code
      run: sqlc generate

    - name: Check for changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated go code"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          NEW_COMMIT_HASH=$(git rev-parse HEAD)
          echo "Pushed changes: [$NEW_COMMIT_HASH](https://github.com/${{ github.repository }}/commit/$NEW_COMMIT_HASH)"  >> $GITHUB_STEP_SUMMARY
        else
          echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
        fi