name: Lint
env:
  GO_VERSION: '1.23'
on:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0